#!/usr/bin/env bash
# displays Best school 9 times and hi at the 9th iteration

i=0
while [ $i -lt 11 ]
do
    if [ $i = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
      ((i++))
done
