#!/usr/bin/env bash
# display hours from 0 to 12,
# and minutes from 1 to 59
minute=1
hour=0
while [[ $hour -le 12 ]];
	do
	echo "Hour: "$hour
	while [[ $minute -le 59 ]];
		do
		echo $minute
		(( minute++ ));
	done;
	(( minute=1 ))
	(( hour++ ));
done;
